spring.application.name=api

spring.datasource.url=jdbc:postgresql://localhost:5432/clarim_diario
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET:chave-de-desenvolvimento-testes-no-ambiente-local-1234}
jwt.expiracao-minutos=60

google.client-id=${GOOGLE_CLIENT_ID: 510274226954-jkhcn1hqsj6vfcmn6dn3lol8msoq4qn8.apps.googleusercontent.com }