spring.application.name=api

spring.datasource.url=jdbc:postgresql://localhost:5432/clarim_diario
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET:chave-de-desenvolvimento-testes-no-ambiente-local-1234}
jwt.expiracao-minutos=60

google.client-id=${GOOGLE_CLIENT_ID:

stripe.secret-key=
stripe.webhook-secret=

app.front-url=http://localhost:5173